# pyright: basic, reportGeneralTypeIssues=false, reportOptionalSubscript=false

import bpy
import mathutils
from ..wce.wce import wce
from typing import Optional
from .worlddef import encode_worlddef
from .actordef import encode_actordef
from .hierarchicalspritedef import encode_hierarchicalspritedef
from .track import encode_track
from .dmspritedef2 import encode_dmspritedef2
from .polyhedrondefinition import encode_polyhedrondefinition
from .materialpalette import encode_materialpalette
from .materialdefinition import encode_materialdefinition
from .simplespritedef import encode_simplespritedef
from ..logger.error import error
from .context import Context
import os

def write_animation_folder(parser, root_path):

    anim_dir = os.path.join(root_path, "animations")
    os.makedirs(anim_dir, exist_ok=True)

    # Group tracks by animation
    anim_groups = {}

    for t in parser.tracks.values():
        if t.is_pose:
            continue

        anim_groups.setdefault(t.animation, []).append(t)

    # Write each animation file
    for anim_name, tracks in anim_groups.items():

        filepath = os.path.join(anim_dir, f"{anim_name.lower()}.wce")

        with open(filepath, "w") as w:

            w.write("// wcemu v0.0.1\n")
            w.write("// Animation file\n\n")

            for t in tracks:
                t.write(w)
                w.write("\n")

def write_materials_and_sprites(parser, w):

    written_sprites = set()

    for tag, mat in parser.materialdefinitions.items():

        sprite_tag = mat.simplespriteinst.simplespritetag

        # ----------------------------------------
        # Write SimpleSprite FIRST (if needed)
        # ----------------------------------------
        if sprite_tag:

            sprite = parser.simplespritedefs.get(sprite_tag)

            if sprite and sprite_tag not in written_sprites:
                sprite.write(w)
                w.write("\n")
                written_sprites.add(sprite_tag)

        # ----------------------------------------
        # Write MaterialDefinition
        # ----------------------------------------
        mat.write(w)
        w.write("\n")

def write_world_wce(parser, root_path):

    world_path = os.path.join(root_path, "world.wce")

    with open(world_path, "w") as w:
        w.write("// wcemu v0.0.1\n")
        w.write("// Generated by exporter\n\n")

        if parser.worlddef:
            parser.worlddef.write(w)
        else:
            # fallback (optional)
            w.write("WORLDDEF\n")
            w.write("\tNEWWORLD 0\n")
            w.write("\tZONE 0\n")
            w.write("\tEQGVERSION? NULL\n")

def write_quail_folder(parser, export_objects, root_path):

    print("Writing quail folder:", root_path)

    os.makedirs(root_path, exist_ok=True)

    write_world_wce(parser, root_path)

    root_file = os.path.join(root_path, "_root.wce")

    with open(root_file, "w") as w:

        w.write("// wcemu v0.0.1\n")
        w.write("// Generated by exporter\n\n")

        w.write("INCLUDE \"WORLD.WCE\"\n\n")

        write_materials_and_sprites(parser, w)

        for tag, obj in parser.materialpalettes.items():
            obj.write(w)
            w.write("\n")

        for tag, obj in parser.polyhedrondefinitions.items():
            obj.write(w)
            w.write("\n")

        for tag, obj in parser.dmspritedef2s.items():
            obj.write(w)
            w.write("\n")

        for t in parser.tracks.values():
            if t.is_pose:
                t.write(w)

        for tag, obj in parser.hierarchicalspritedefs.items():
            obj.write(w)
            w.write("\n")

        for tag, obj in parser.actordefs.items():
            obj.write(w)
            w.write("\n")

    write_animation_folder(parser, root_path)

    return ""

def gather_export_tracks(export_objects):

    actions = set()

    # ----------------------------------------
    # Find HS_DEF armatures
    # ----------------------------------------
    for obj in export_objects:

        if not isinstance(obj, bpy.types.Object):
            continue

        if obj.type != 'ARMATURE':
            continue

        if obj.get("quaildef") != "hierarchicalspritedef":
            continue

        model_code = obj.name.replace("_HS_DEF", "")

        # ----------------------------------------
        # Direct action on armature (strongest link)
        # ----------------------------------------
        if obj.animation_data and obj.animation_data.action:
            actions.add(obj.animation_data.action)

        # ----------------------------------------
        # Also gather matching actions by name
        # ----------------------------------------
        for action in bpy.data.actions:
            if action.get("quaildef") != "track":
                continue

            # Match "_AVI", "_HUM", etc
            if action.name.endswith(f"_{model_code}"):
                actions.add(action)

    return actions

def gather_export_objects(root_objects):
    visited = set()
    stack = list(root_objects)

    def add(obj):
        if obj and obj not in visited:
            stack.append(obj)

    while stack:
        obj = stack.pop()

        if obj in visited:
            continue

        visited.add(obj)

        # ----------------------------------------
        # Children (ONLY for Blender Objects)
        # ----------------------------------------
        if isinstance(obj, bpy.types.Object):
            for child in obj.children:
                add(child)

        # ----------------------------------------
        # Safe quaildef access
        # ----------------------------------------
        qdef = obj.get("quaildef") if hasattr(obj, "get") else None

        # ----------------------------------------
        # DMSPRITE → MATERIALPALETTE
        # ----------------------------------------
        if qdef == "dmspritedef2":
            props = obj.quail_dmspritedef2
            if props.materialpalette:
                add(props.materialpalette)

        elif qdef == "dmspritedefinition":
            props = obj.quail_dmspritedefinition
            if props.materialpalette:
                add(props.materialpalette)

        # ----------------------------------------
        # MATERIALPALETTE → MATERIALDEFINITION → SIMPLESPRITEDEF
        # ----------------------------------------
        elif qdef == "materialpalette":
            props = obj.quail_materialpalette

            for item in props.materials:
                mat = item.material
                if not mat:
                    continue

                # Add Blender Material
                add(mat)

                # ----------------------------------------
                # MATERIALDEFINITION
                # ----------------------------------------
                if mat.get("quaildef") == "materialdefinition":

                    mprops = mat.quail_materialdefinition
                    sprite_tag = mprops.simplespritetag

                    # ----------------------------------------
                    # SIMPLESPRITEDEF (NodeTree)
                    # ----------------------------------------
                    if sprite_tag and sprite_tag != "NONE":
                        sprite = bpy.data.node_groups.get(sprite_tag)

                        if sprite:
                            add(sprite)
                        else:
                            print(
                                f"WARNING: Missing SimpleSpriteDef '{sprite_tag}' "
                                f"for material '{mat.name}'"
                            )

    return visited

def wce_encode(folder_path: str, context, selected_only: bool) -> str:

    # ------------------------------------------------
    # Setup parser (same class as decode)
    # ------------------------------------------------
    parser = wce(folder_path)

    errors = []

    # ------------------------------------------------
    # Build root set
    # ------------------------------------------------
    if selected_only:

        if context.selected_objects:
            root_objects = list(context.selected_objects)

        else:
            # ----------------------------------------
            # Fallback: use active collection
            # ----------------------------------------
            col = context.collection

            if col:
                root_objects = list(col.objects)
            else:
                root_objects = []

    # ------------------------------------------------
    # Gather dependency graph
    # ------------------------------------------------
    export_objects = gather_export_objects(root_objects)
    export_actions = gather_export_tracks(export_objects)

    print("Export set:")
    for obj in export_objects:
        print("  ", obj.name, obj.get("quaildef"))

    # ------------------------------------------------
    # Find WORLDDEF collection
    # ------------------------------------------------
    world_collection = None

    for obj in export_objects:
        if isinstance(obj, bpy.types.Object):
            for col in obj.users_collection:
                if col.get("quaildef") == "worlddef":
                    world_collection = col
                    break
        if world_collection:
            break

    if world_collection:
        err = encode_worlddef(parser, world_collection)
        if err:
            errors.append(err)

    # ------------------------------------------------
    # Gather Blender objects by type (FILTERED SET)
    # ------------------------------------------------
    actordefs = []
    simplesprites = []
    materialdefs = []
    materialpalettes = []
    polyhedrons = []
    dmsprite_defs = []
    dmsprite2_defs = []
    tracks = []
    hierarchicalsprites = []
    eqgmodels = []
    eqgters = []
    eqganis = []

    for obj in export_objects:

        qdef = obj.get("quaildef")

        if not qdef:
            continue

        if qdef == "actordef":
            actordefs.append(obj)

        elif qdef == "hierarchicalspritedef":
            hierarchicalsprites.append(obj)

        elif qdef == "dmspritedefinition":
            dmsprite_defs.append(obj)

        elif qdef == "dmspritedef2":
            dmsprite2_defs.append(obj)

        elif qdef == "polyhedrondefinition":
            polyhedrons.append(obj)

        elif qdef == "materialpalette":
            materialpalettes.append(obj)

        elif qdef == "materialdefinition":
            materialdefs.append(obj)

        elif qdef == "simplespritedef":
            simplesprites.append(obj)

        elif qdef == "eqgmodeldef":
            eqgmodels.append(obj)

        elif qdef == "eqgterdef":
            eqgters.append(obj)

        elif qdef == "eqganidef":
            eqganis.append(obj)

    # ------------------------------------------------
    # Encode (order matters!)
    # ------------------------------------------------

    for obj in actordefs:
        err = encode_actordef(parser, obj)
        if err:
            errors.append(err)

    for obj in hierarchicalsprites:
        err = encode_hierarchicalspritedef(parser, obj)
        if err:
            errors.append(err)

    err = encode_track(parser, export_actions, context)
    if err:
        errors.append(err)


    # for obj in dmsprite_defs:
    #     err = encode_dmspritedefinition(parser, obj)
    #     if err:
    #         errors.append(err)

    for obj in dmsprite2_defs:
        err = encode_dmspritedef2(parser, obj)
        if err:
            errors.append(err)

    for obj in polyhedrons:
        err = encode_polyhedrondefinition(parser, obj)
        if err:
            errors.append(err)

    for obj in materialpalettes:
        err = encode_materialpalette(parser, obj)
        if err:
            errors.append(err)

    for obj in materialdefs:
        err = encode_materialdefinition(parser, obj)
        if err:
            errors.append(err)

    for obj in simplesprites:
        err = encode_simplespritedef(parser, obj)
        if err:
            errors.append(err)

    # for obj in eqgters:
    #     err = encode_eqgterdef(parser, obj)
    #     if err:
    #         errors.append(err)

    # for obj in eqgmodels:
    #     err = encode_eqgmodeldef(parser, obj)
    #     if err:
    #         errors.append(err)

    # for obj in eqganis:
    #     err = encode_eqganidef(parser, obj)
    #     if err:
    #         errors.append(err)

    # ------------------------------------------------
    # Write full quail folder structure
    # ------------------------------------------------
    err = write_quail_folder(parser, export_objects, folder_path)

    if err:
        return err

    # ------------------------------------------------
    # Return errors if any
    # ------------------------------------------------
    if errors:
        return "\n".join(errors)

    return ""